# Generated by Django 4.0.2 on 2023-05-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='joindate',
        ),
    ]
