# Generated by Django 4.0.2 on 2023-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0002_remove_data_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='joindate',
            field=models.DateField(auto_now=True),
        ),
    ]
