# Generated by Django 4.0.2 on 2023-06-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0006_alter_data_joindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
        migrations.RemoveField(
            model_name='data',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
    ]
